# Generated by Django 4.1.7 on 2023-02-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    atomic = False
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song1_id", models.CharField(max_length=50)),
                ("song1_name_artist", models.CharField(max_length=300)),
                ("song2_id", models.CharField(max_length=50)),
                ("song2_name_artist", models.CharField(max_length=300)),
                ("song3_id", models.CharField(max_length=50)),
                ("song3_name_artist", models.CharField(max_length=300)),
                ("song4_id", models.CharField(max_length=50)),
                ("song4_name_artist", models.CharField(max_length=300)),
                ("song5_id", models.CharField(max_length=50)),
                ("song5_name_artist", models.CharField(max_length=300)),
                ("artist1_id", models.CharField(max_length=50)),
                ("artist1_name", models.CharField(max_length=300)),
                ("artist2_id", models.CharField(max_length=50)),
                ("artist2_name", models.CharField(max_length=300)),
                ("artist3_id", models.CharField(max_length=50)),
                ("artist3_name", models.CharField(max_length=300)),
                ("artist4_id", models.CharField(max_length=50)),
                ("artist4_name", models.CharField(max_length=300)),
                ("artist5_id", models.CharField(max_length=50)),
                ("artist5_name", models.CharField(max_length=300)),
                ("album1_id", models.CharField(max_length=50)),
                ("album1_name_artist", models.CharField(max_length=300)),
                ("album2_id", models.CharField(max_length=50)),
                ("album2_name_artist", models.CharField(max_length=300)),
                ("album3_id", models.CharField(max_length=50)),
                ("album3_name_artist", models.CharField(max_length=300)),
                ("album4_id", models.CharField(max_length=50)),
                ("album4_name_artist", models.CharField(max_length=300)),
                ("album5_id", models.CharField(max_length=50)),
                ("album5_name_artist", models.CharField(max_length=300)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.user",
                    ),
                ),
            ],
        ),
    ]
