# Generated by Django 4.1.7 on 2023-02-27 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_favoritealbum_favoriteartist_favoritesong_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoritesong",
            old_name="user_id",
            new_name="user",
        ),
    ]
