# Generated by Django 4.1.7 on 2023-02-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("application", "0004_rename_user_id_favoritesong_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritesong",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
    ]
