# Generated by Django 4.1.7 on 2023-02-27 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_alter_favoritesong_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritesong",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
    ]
