# Generated by Django 4.1.7 on 2023-02-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0007_rename_user_id_favoritealbum_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritesong",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
    ]
