# Generated by Django 3.2.18 on 2023-03-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("application", "0009_alter_favoritealbum_user_alter_favoriteartist_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre1", models.CharField(max_length=300)),
                ("genre2", models.CharField(max_length=300)),
                ("genre3", models.CharField(max_length=300)),
                ("genre4", models.CharField(max_length=300)),
                ("genre5", models.CharField(max_length=300)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.user",
                    ),
                ),
            ],
        ),
    ]
