# Generated by Django 3.2.18 on 2023-03-01 15:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("application", "0010_favoritegenre_genrelist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrelist",
            old_name="genre",
            new_name="genre_name",
        ),
    ]
