# Generated by Django 3.2.18 on 2023-03-09 23:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("application", "0012_promptlist_userprompts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="usertest",
        ),
    ]
