# Generated by Django 3.2.18 on 2023-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="dislikes",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="likes",
            name="likes",
            field=models.JSONField(default=list),
        ),
    ]
