# Generated by Django 3.2.18 on 2023-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20230325_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='matches',
            field=models.JSONField(default=list),
        ),
    ]
