# Generated by Django 3.2.18 on 2023-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0018_likes_matches"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_picture",
            field=models.ImageField(
                default="images/placeholder.png", upload_to="images/"
            ),
        ),
    ]
